# Variational Quantum Classifier (VQC) for Iris Classification


This notebook explores the application of the [Variational Quantum Classifier (VQC)](https://qiskit.org/ecosystem/machine-learning/stubs/qiskit_machine_learning.algorithms.VQC.html) algorithm for the classification of the famous [Iris dataset](https://en.wikipedia.org/wiki/Iris_flower_data_set). The VQC is a cutting-edge quantum algorithm designed for classification tasks. Leveraging the principles of variational circuits, the VQC combines classical and quantum computing to efficiently classify input data. In this notebook, we delve into the implementation and training of the VQC algorithm, unraveling its potential in handling classification challenges. In this context, we aim to train the VQC to classify different species of iris flowers based on features such as sepal length, sepal width, petal length, and petal width. 

## Importing Libraries

In [115]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
from qiskit import BasicAer
from qiskit.circuit.library import ZZFeatureMap
from qiskit_machine_learning.algorithms import VQC
from qiskit.algorithms.optimizers import COBYLA
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [126]:
# Set random seed for reproducibility
np.random.seed(60)

## Loading the Iris Dataset

In [127]:
iris = datasets.load_iris()
features = iris.data
labels = iris.target

In [128]:
# Printing the first 5 rows of the features of the dataset

print("First 5 rows of the features of the dataset:\n")
print(features[:5])

First 5 rows of the features of the dataset:

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [129]:
# Printing the first 5 labels

print("First 5 labels of the dataset:\n")
print(labels[:5])

First 5 labels of the dataset:

[0 0 0 0 0]


## Preprocessing the data

In [130]:
features = MinMaxScaler(feature_range=(0, 1)).fit_transform(features)

print("Features after applying MinMaxScaler:\n")
print(features[:5])

Features after applying MinMaxScaler:

[[0.22222222 0.625      0.06779661 0.04166667]
 [0.16666667 0.41666667 0.06779661 0.04166667]
 [0.11111111 0.5        0.05084746 0.04166667]
 [0.08333333 0.45833333 0.08474576 0.04166667]
 [0.19444444 0.66666667 0.06779661 0.04166667]]


In [131]:
# Splitting the dataset into training and test sets

train_features, test_features, train_labels, test_labels = train_test_split(features, labels, train_size=0.8, random_state=30)

## Quantum Feature Map

In [132]:
# Set up quantum feature map
num_qubits = features.shape[1]
feature_map = ZZFeatureMap(feature_dimension=num_qubits, reps=2, entanglement="linear")
print(feature_map)

     ┌────────────────────────────────────┐
q_0: ┤0                                   ├
     │                                    │
q_1: ┤1                                   ├
     │  ZZFeatureMap(x[0],x[1],x[2],x[3]) │
q_2: ┤2                                   ├
     │                                    │
q_3: ┤3                                   ├
     └────────────────────────────────────┘


## Setting up and training the VQC model

In [133]:
# Set up VQC model with COBYLA optimizer
optimizer = COBYLA(maxiter=100)
vqc = VQC(optimizer=optimizer, feature_map=feature_map)

# Train the VQC model
vqc.fit(train_features, train_labels)


In [134]:
# Predicting labels for test_features

pred_labels = vqc.predict(test_features)

## Model Accuracy

In [135]:
# Calculate accuracy using accuracy_score
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test_labels, pred_labels)
print("VQC classification test accuracy:", accuracy)

VQC classification test accuracy: 0.9


The accuracy of the model may differ each time you execute it because quantum circuits involve random processes. Quantum computing introduces inherent variability, leading to slightly different outcomes with each run.
